### ISSUE TITLE
dataset_info.json

### ISSUE THREAD

**Issue by yjh576** [jessemelpolio/AnytimeCL#1]
Sorry, I cannot find this file: dataset_info.json. Could you give me help? Thank you in advance.

**Comment by jessemelpolio** [comment]
Hi, I guess you will need to follow the instructions on [how to prepare the dataset](https://github.com/jessemelpolio/AnytimeCL?tab=readme-ov-file#usage). The json file should be produced by [this code](https://github.com/jessemelpolio/AnytimeCL/blob/ca7697c2b46fa6be473e45fdf776fda214f8a919/encode_features/compress_clip_intermediate_features.py#L39).

Please let me know if I have missed anything or you need additional help.

**Comment by yjh576** [comment]
It works for me. Thanks!
